 module.exports = {

  getting_started: [
    "getting-started/introduction",
    "getting-started/faq",
    {
      type: 'category',
      label: 'How to guides',
      items: [
        {
          type: 'autogenerated',
          dirName: 'getting-started/how-to-guides',
        } 
      ] 
    },
  ],
  developers: [
    "developers/introduction",
    "developers/deployed-contracts",
      {
      type: 'category',
      label: 'Smart Contracts',
        items: [
          {
            type: 'autogenerated',
            dirName: 'developers/contracts',
          } 
        ] 
    },
  ]

};